# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68e6162d3edecf350044f47927ed4e819a23d68b086ae9b00a643931c552d726a94ea69cc776226c7470d5cd0e7d400c581e10ca93a028d25b4154e9d3678c1a

test:
  secret_key_base: e94fb250eae58efdd5dcdf04f82a3234e0c08e4a8c20085fb485dbbe99b133f4a58f00b8345d7cb1ad2d62227e145851f1e3a0d663b228c7892b002e3427734b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
